(() => {
'use strict';
const K={games:'ipbooster.games.v1',router:'ipbooster.smartplay.v4',device:'ipbooster.device.v1',quick:'ipbooster.quicknet.v3',full:'ipbooster.network.v1',pending:'ipbooster.pending-session.v2',cfg:'ipbooster.performance.v1'};
const P={competitive:{label:'Competitive',age:300000,n:4,lat:80,jit:20,batt:25,lpm:false,steps:['Set Focus → Gaming → On','Set Low Power Mode → Off']},balanced:{label:'Balanced',age:900000,n:3,lat:120,jit:30,batt:15,lpm:false,steps:['Set Focus → Gaming → On','Set Low Power Mode → Off (recommended)']},battery:{label:'Battery Saver',age:1800000,n:2,lat:150,jit:40,batt:10,lpm:true,steps:['Set Focus → Gaming → On','Set Low Power Mode → On']}};
const $=s=>document.querySelector(s),load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),enc=v=>encodeURIComponent(String(v??'')).replace(/[!'()*]/g,c=>`%${c.charCodeAt(0).toString(16).toUpperCase()}`),esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const games=()=>{const x=load(K.games,[]);return Array.isArray(x)?x:[]},game=id=>games().find(g=>String(g.id)===String(id)),router=()=>load(K.router,{}),policy=g=>P[g?.profile]||P.balanced,route=g=>router().targets?.[g.id]?.routeKey?.trim()||g.name,ready=()=>Boolean(router().universalReady&&router().universalShortcut?.trim()),cfg=()=>({enabled:true,autoCheck:true,prep:{},...load(K.cfg,{})});
function bool(v){if(typeof v==='boolean')return v;if(typeof v==='number')return !!v;v=String(v??'').toLowerCase();if(['on','true','1','yes','enabled'].includes(v))return true;if(['off','false','0','no','disabled'].includes(v))return false;return null}
function device(){const d=load(K.device,null);if(!d||typeof d!=='object')return null;let b=Number(String(d.battery??d.batteryLevel??d.level??'').replace('%',''));if(!Number.isFinite(b))b=null;if(b!==null&&b<=1)b*=100;return{battery:b,lpm:bool(d.lowPowerMode??d.low_power_mode??d.lpm),focus:d.focus??d.focusMode??d.currentFocus??null,charging:bool(d.charging??d.isCharging)}}
function net(){const q=load(K.quick,null),f=load(K.full,[]),x=Array.isArray(f)?f[0]:null;return q&&(!x||Number(q.at)>=Number(x.at))?q:x}
function prep(g){const x=cfg().prep?.[g.id];return Boolean(x?.at&&x?.profile===(g.profile||'balanced'))}
function assess(g,n=net()){const p=policy(g),d=device(),fresh=Boolean(n?.at&&Date.now()-Number(n.at)<=p.age),bad=Boolean(n&&(Number(n.latency)>p.lat||Number(n.jitter)>p.jit)),lpmConflict=d?.lpm!=null&&d.lpm!==p.lpm,battLow=d?.battery!=null&&d.battery<p.batt&&!d.charging,ps=prep(g);let score=ready()?25:0;score+=ps?25:0;score+=fresh&&!bad?25:n&&!bad?12:0;score+=lpmConflict?0:d?.lpm==null?5:10;score+=battLow?0:d?.battery==null?5:10;return{p,d,n,fresh,bad,lpmConflict,battLow,ps,score:Math.min(100,score),risk:!ready()||bad?'High':lpmConflict||battLow||!ps?'Medium':fresh?'Low':'Medium'}}
function med(a){a=[...a].sort((x,y)=>x-y);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
async function quick(g,progress){const a=[],p=policy(g);for(let i=0;i<p.n;i++){progress?.(i,p.n);const c=new AbortController(),t=setTimeout(()=>c.abort(),3500),s=performance.now();try{const r=await fetch(`https://speed.cloudflare.com/__down?bytes=1&ipbp=${Date.now()}-${i}`,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error('HTTP');await r.arrayBuffer();a.push(performance.now()-s)}finally{clearTimeout(t)}}const dif=a.slice(1).map((v,i)=>Math.abs(v-a[i])),r={at:Date.now(),latency:Math.round(med(a)*10)/10,jitter:Math.round(avg(dif)*10)/10,source:'Performance preflight'};save(K.quick,r);return r}
function recipe(g){const s=[...policy(g).steps,`Buka App → ${g.name}`];return games().length<=1?s:[`Jika Shortcut Input adalah “${route(g)}”`,...s]}
function launch(g,a){save(K.pending,{id:crypto.randomUUID?.()||String(Date.now()),gameId:g.id,gameName:g.name,artworkUrl:g.artworkUrl||'',appStoreId:g.appStoreId||'',profile:g.profile||'balanced',startedAt:Date.now(),performance:{score:a.score,risk:a.risk,prep:a.ps,network:a.n||null}});const r=router(),url=r.targets?.[g.id]?.deepLink?.trim();location.href=url||`shortcuts://run-shortcut?name=${enc(r.universalShortcut||'iPBooster Play')}&input=text&text=${enc(route(g))}`}
function ui(){if(!$('#perfStyle')){const s=document.createElement('style');s.id='perfStyle';s.textContent='.perf-card{margin:14px 0;padding:16px;border-radius:22px}.perf-head{display:flex;justify-content:space-between;gap:12px}.perf-badge{font-size:10px;font-weight:800;color:var(--accent)}.perf-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.perf-grid div,.perf-row{padding:10px;border-radius:13px;background:rgba(255,255,255,.045)}.perf-grid span,.perf-row span{display:block;color:var(--muted);font-size:9px}.perf-grid strong,.perf-row strong{font-size:12px}.perf-rows{display:grid;gap:8px;margin:12px 0}.perf-row{display:flex;justify-content:space-between;gap:12px}.perf-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.perf-actions button{margin:0}.perf-step{padding:10px;margin:7px 0;border-radius:12px;background:rgba(0,0,0,.2);font-size:11px}.perf-note{font-size:10px;color:var(--muted);line-height:1.5;margin-top:12px}@media(max-width:430px){.perf-actions{grid-template-columns:1fr}}';document.head.appendChild(s)}if(!$('#perfDialog'))document.body.insertAdjacentHTML('beforeend','<dialog id="perfDialog" class="modal"><div class="modal-card glass strong-glass"><div class="modal-head"><div><p class="eyebrow">PERFORMANCE ENGINE v3.1</p><h2 id="perfTitle">Performance Mode</h2></div><button class="close-button" data-perf-close>×</button></div><div id="perfBody"></div></div></dialog>');const h=$('[data-view="home"]');if(h&&!$('#perfCard')){const c=document.createElement('section');c.id='perfCard';c.className='perf-card glass strong-glass';h.querySelector('.metrics-grid')?.insertAdjacentElement('afterend',c)}}
function focusGame(){const a=games(),s=load('ipbooster.sessions.v2',[]),l=Array.isArray(s)?s[0]:null;return l?a.find(g=>String(g.id)===String(l.gameId))||a[0]:a[0]}
function card(){const v=$('.version-chip');if(v)v.textContent='v3.1';document.title='iPBooster v3.1 — iOS 26+ Gaming Control';const r=$('#perfCard'),g=focusGame();if(!r)return;if(!g){r.innerHTML='<div class="perf-head"><div><p class="eyebrow">PERFORMANCE ENGINE</p><h3>Add a game</h3></div><span class="perf-badge">REAL iOS PREP</span></div>';return}const a=assess(g);r.innerHTML=`<div class="perf-head"><div><p class="eyebrow">PERFORMANCE ENGINE</p><h3>${esc(g.name)}</h3><small>${esc(a.p.label)} · native Game Mode handoff</small></div><span class="perf-badge">${a.score}/100</span></div><div class="perf-grid"><div><span>Stability risk</span><strong>${a.risk}</strong></div><div><span>System prep</span><strong>${a.ps?'Synced':'Needs setup'}</strong></div><div><span>Network</span><strong>${a.fresh?'Fresh':'Check needed'}</strong></div></div><div class="perf-actions"><button class="secondary-button" data-perf-recipe="${esc(g.id)}">System Recipe</button><button class="primary-button" data-perf-play="${esc(g.id)}">Performance Play</button></div>`}
function body(g,n=net(),checking=false){const a=assess(g,n),d=a.d,rows=[['Launch route',ready()?'Ready':'Setup required'],['System prep',a.ps?`${a.p.label} synced`:'Recipe not confirmed'],['Network',a.n?`${a.n.latency} ms · ${a.n.jitter} ms jitter${a.fresh?'':' · stale'}`:'Not measured'],['Low Power Mode',d?.lpm==null?`Unknown · target ${a.p.lpm?'ON':'OFF'}`:`${d.lpm?'ON':'OFF'} · target ${a.p.lpm?'ON':'OFF'}`],['Battery',d?.battery==null?'Unknown':`${Math.round(d.battery)}%${d.charging?' · charging':''}`],['Gaming Focus',d?.focus||'Unknown'],['Native Game Mode','Automatic after supported game opens'],['Thermal / in-game FPS','Not exposed to PWA']];$('#perfTitle').textContent=g.name;$('#perfBody').innerHTML=`<p class="page-intro" style="margin-top:0">${esc(a.p.label)} · readiness ${a.score}/100 · stability risk ${a.risk}</p><div class="perf-rows">${rows.map(x=>`<div class="perf-row"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('')}</div>${checking?'<div class="test-progress"><div class="progress-track"><div id="perfBar"></div></div><p id="perfText">Checking latency…</p></div>':''}${a.bad?'<div class="smart-warning">Network jitter/latency tinggi. Ini dapat terasa seperti stutter walau rendering FPS game sendiri stabil.</div>':''}${!a.ps?'<div class="smart-warning">System prep belum dikonfirmasi. Tambahkan Focus/Low Power Mode recipe ke Shortcut.</div>':''}<div class="perf-actions"><button class="secondary-button" data-perf-recipe="${esc(g.id)}">System Recipe</button><button class="secondary-button" data-perf-recheck="${esc(g.id)}">Quick Recheck</button><button class="primary-button" data-perf-launch="${esc(g.id)}" ${ready()?'':'disabled'}>Launch Game</button></div><p class="perf-note">Engine ini tidak mengunci FPS/clock atau membaca suhu SoC. Game Mode native iOS yang memberi game prioritas CPU/GPU tertinggi; iPBooster menyiapkan kondisi launch yang bisa dikontrol secara sah.</p>`;return a}
async function open(g,force=false){ui();$('#perfDialog').showModal();let a=body(g);if(!cfg().autoCheck||(!force&&a.fresh))return;body(g,null,true);try{const n=await quick(g,(i,c)=>{const b=$('#perfBar'),t=$('#perfText');if(b)b.style.width=`${Math.round((i+1)/c*100)}%`;if(t)t.textContent=`Latency sample ${i+1}/${c}…`});body(g,n);card()}catch(e){body(g);$('#perfBody')?.insertAdjacentHTML('afterbegin','<div class="smart-warning">Quick check gagal. Game masih bisa diluncurkan jika Router siap.</div>')}}
function showRecipe(g){ui();const a=assess(g),steps=recipe(g);$('#perfTitle').textContent=`${g.name} · System Prep`;$('#perfBody').innerHTML=`<p class="page-intro" style="margin-top:0">${games().length<=1?'Karena library baru satu game, letakkan langkah ini langsung sebelum Buka App.':'Tambahkan langkah ini pada cabang router game.'}</p>${steps.map((s,i)=>`<div class="perf-step"><b>${i+1}.</b> ${esc(s)}</div>`).join('')}<p class="perf-note">Competitive memakai Low Power Mode OFF. Gaming Focus mengurangi gangguan. Game Mode tetap otomatis oleh iOS. Kamu bisa membuat Automation App → Ditutup → Set Focus Gaming Off untuk memulihkan Focus setelah bermain.</p><div class="perf-actions"><button class="secondary-button" data-perf-open>Open iPBooster Play</button><button class="primary-button" data-perf-confirm="${esc(g.id)}">${a.ps?'✓ Recipe Confirmed':'I Added These Actions'}</button></div>`;$('#perfDialog').showModal()}
function confirm(g){const c=cfg();c.prep||={};c.prep[g.id]={profile:g.profile||'balanced',at:Date.now()};save(K.cfg,c);showRecipe(g);card()}
function bind(){document.addEventListener('click',e=>{if(e.target.closest?.('[data-perf-close]')){$('#perfDialog')?.close();return}const rb=e.target.closest?.('[data-perf-recipe]');if(rb){e.preventDefault();e.stopImmediatePropagation();const g=game(rb.dataset.perfRecipe);if(g)showRecipe(g);return}const cf=e.target.closest?.('[data-perf-confirm]');if(cf){e.preventDefault();const g=game(cf.dataset.perfConfirm);if(g)confirm(g);return}if(e.target.closest?.('[data-perf-open]')){e.preventDefault();location.href=`shortcuts://open-shortcut?name=${enc(router().universalShortcut||'iPBooster Play')}`;return}const rc=e.target.closest?.('[data-perf-recheck]');if(rc){e.preventDefault();e.stopImmediatePropagation();const g=game(rc.dataset.perfRecheck);if(g)open(g,true);return}const pp=e.target.closest?.('[data-perf-play]');if(pp){e.preventDefault();e.stopImmediatePropagation();const g=game(pp.dataset.perfPlay);if(g)open(g);return}const lg=e.target.closest?.('[data-perf-launch]');if(lg){e.preventDefault();e.stopImmediatePropagation();const g=game(lg.dataset.perfLaunch);if(g){const a=assess(g);$('#perfDialog')?.close();launch(g,a)}return}const p=e.target.closest?.('[data-game-play],[data-v3-preflight]');if(!p||!ready()||cfg().enabled===false)return;const g=game(p.dataset.gamePlay||p.dataset.v3Preflight);if(!g)return;e.preventDefault();e.stopImmediatePropagation();open(g)},true)}
ui();card();bind();const o=new MutationObserver(()=>{clearTimeout(o.t);o.t=setTimeout(()=>{ui();card()},180)});o.observe(document.body,{childList:true,subtree:false});addEventListener('pageshow',()=>setTimeout(card,700));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setTimeout(card,700)});
})();