(() => {
  'use strict';

  const K={games:'ipbooster.games.v1',router:'ipbooster.smartplay.v4',sessions:'ipbooster.sessions.v2',pending:'ipbooster.pending-session.v2',fullNet:'ipbooster.network.v1',quickNet:'ipbooster.quicknet.v3',prefs:'ipbooster.v3.prefs',favs:'ipbooster.v3.favorites',verified:'ipbooster.v3.verified-routes',lastLaunch:'ipbooster.v3.last-launch',seen:'ipbooster.v3.last-seen-session'};
  const P={competitive:{label:'Competitive',note:'Low-latency checks first',age:300000,lat:80,jit:20,samples:4,hint:'Gaming Focus ON · Low Power Mode OFF (optional)'},balanced:{label:'Balanced',note:'Normal checks with less friction',age:900000,lat:120,jit:30,samples:3,hint:'Gaming Focus ON · keep power settings as-is'},battery:{label:'Battery Saver',note:'Lightweight checks to reduce overhead',age:1800000,lat:150,jit:40,samples:2,hint:'Gaming Focus ON · Low Power Mode ON (optional)'}};
  const PREFS={preflight:true,quick:true,post:true};
  let checking=false,preflightResult=null;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const enc=v=>encodeURIComponent(String(v??'')).replace(/[!'()*]/g,c=>`%${c.charCodeAt(0).toString(16).toUpperCase()}`);
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const games=()=>{const v=load(K.games,[]);return Array.isArray(v)?v:[]};
  const sessions=()=>{const v=load(K.sessions,[]);return Array.isArray(v)?v:[]};
  const router=()=>load(K.router,{});
  const favs=()=>{const v=load(K.favs,[]);return Array.isArray(v)?v.map(String):[]};
  const verified=()=>load(K.verified,{});
  const prefs=()=>({...PREFS,...load(K.prefs,{})});
  const gameById=id=>games().find(g=>String(g.id)===String(id));
  const policy=g=>P[g?.profile]||P.balanced;
  const routeKey=g=>router().targets?.[g.id]?.routeKey?.trim()||String(g.name||'').trim();
  const deepLink=g=>router().targets?.[g.id]?.deepLink?.trim()||'';
  const routerReady=()=>Boolean(router().universalReady&&router().universalShortcut?.trim());
  const launchReady=g=>Boolean(deepLink(g)||routerReady());
  const isVerified=g=>Boolean(verified()[g.id]?.verifiedAt);
  const profileLabel=g=>policy(g).label;

  function toast(msg,ms=3200){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),ms)}
  function duration(sec){sec=Number(sec)||0;if(sec<60)return`${Math.max(1,Math.round(sec))}s`;const m=Math.round(sec/60);if(m<60)return`${m}m`;const h=Math.floor(m/60),r=m%60;return r?`${h}h ${r}m`:`${h}h`}
  function median(a){const s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
  function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
  function quality(l,j){l=Number(l);j=Number(j);if(!Number.isFinite(l)||!Number.isFinite(j))return{label:'Unknown',good:false};if(l<=35&&j<=8)return{label:'Excellent',good:true};if(l<=65&&j<=15)return{label:'Good',good:true};if(l<=110&&j<=28)return{label:'Playable',good:true};return{label:'Unstable',good:false}}
  function latestNet(){const q=load(K.quickNet,null),f=load(K.fullNet,[]),x=Array.isArray(f)?f[0]:null;if(q&&(!x||Number(q.at)>=Number(x.at)))return{...q,source:'Quick check'};return x?{...x,source:'Full test'}:null}
  function fresh(g,n=latestNet()){return Boolean(n?.at&&Date.now()-Number(n.at)<=policy(g).age)}
  function warn(g,n){if(!n)return'No network measurement yet';const p=policy(g);return Number(n.latency)>p.lat||Number(n.jitter)>p.jit?`${n.latency} ms / ${n.jitter} ms jitter is above the ${p.label} warning threshold`:''}
  function art(g){return g?.artworkUrl?`<img class="v3-art" src="${esc(g.artworkUrl)}" alt="${esc(g.name)} official App Store icon" referrerpolicy="no-referrer">`:`<span class="v3-art" style="display:grid;place-items:center;font-size:24px">🎮</span>`}

  function beginSession(g){save(K.pending,{id:crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`,gameId:g.id,gameName:g.name,artworkUrl:g.artworkUrl||'',appStoreId:g.appStoreId||'',profile:g.profile||'balanced',startedAt:Date.now()});save(K.lastLaunch,{gameId:g.id,gameName:g.name,at:Date.now(),profile:g.profile||'balanced',network:preflightResult||latestNet()})}
  function launchURL(g){const r=router(),name=r.universalShortcut?.trim()||'iPBooster Play';return`shortcuts://run-shortcut?name=${enc(name)}&input=text&text=${enc(routeKey(g))}`}
  function launch(g){if(!g)return;beginSession(g);location.href=deepLink(g)||launchURL(g)}

  async function ping(i){const c=new AbortController(),t=setTimeout(()=>c.abort(),3200),start=performance.now();try{const r=await fetch(`https://speed.cloudflare.com/__down?bytes=1&ipb=${Date.now()}-${i}`,{cache:'no-store',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);await r.arrayBuffer();return performance.now()-start}finally{clearTimeout(t)}}
  async function quickCheck(g,onProgress){if(!navigator.onLine)throw new Error('offline');const a=[],count=Math.max(2,policy(g).samples);for(let i=0;i<count;i++){onProgress?.(i,count);a.push(await ping(i))}const d=a.slice(1).map((v,i)=>Math.abs(v-a[i])),r={at:Date.now(),latency:Math.round(median(a)*10)/10,jitter:Math.round(avg(d)*10)/10,source:'Quick check'};save(K.quickNet,r);return r}

  function stats(g){const l=sessions().filter(x=>String(x.gameId)===String(g.id)||x.gameName===g.name),total=l.reduce((s,x)=>s+(Number(x.durationSec)||0),0);return{launches:l.length,total,avg:l.length?total/l.length:0,last:l[0]||null}}
  function readiness(g){const n=latestNet(),checks=[];let score=0;const launchOk=launchReady(g);if(launchOk)score+=30;checks.push({label:deepLink(g)?'Direct link configured':launchOk?'Router configured':'Router setup needed',good:launchOk});const v=isVerified(g);if(v)score+=20;checks.push({label:v?'Route verified':'Route unverified',good:v});const f=fresh(g,n);if(f)score+=25;checks.push({label:f?`${n.latency} ms network`:'Network stale',good:f});if(g.artworkUrl)score+=10;checks.push({label:g.artworkUrl?'Official artwork':'Artwork pending',good:Boolean(g.artworkUrl)});const standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(standalone)score+=15;checks.push({label:standalone?'Home Screen PWA':'Safari mode',good:standalone});return{score:Math.min(100,score),checks}}

  function dialogs(){
    if(!$('#v3GameDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="v3GameDialog" class="modal"><div class="modal-card glass strong-glass"><div class="modal-head"><div><p class="eyebrow">GAME CONTROL</p><h2 id="v3GameTitle">Game</h2></div><button type="button" class="close-button" data-v3-close="v3GameDialog">×</button></div><div id="v3GameContent"></div></div></dialog>`);
    if(!$('#v3PreflightDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="v3PreflightDialog" class="modal"><div class="modal-card glass strong-glass"><div class="modal-head"><div><p class="eyebrow">SMART LAUNCH v3</p><h2 id="v3PreflightTitle">Preparing game</h2></div><button type="button" class="close-button" data-v3-close="v3PreflightDialog">×</button></div><div id="v3PreflightContent"></div></div></dialog>`);
    if(!$('#v3RouterDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="v3RouterDialog" class="modal"><div class="modal-card glass strong-glass"><div class="modal-head"><div><p class="eyebrow">ROUTER + PROFILE ASSISTANT</p><h2>Shortcut map</h2></div><button type="button" class="close-button" data-v3-close="v3RouterDialog">×</button></div><p class="page-intro" style="margin-top:0">Web tidak bisa mengedit isi Shortcut. Assistant ini menunjukkan cabang yang harus ada dan profile policy yang benar-benar dipakai sebelum launch.</p><div id="v3RouterContent"></div></div></dialog>`);
    if(!$('#v3PostDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="v3PostDialog" class="modal"><div class="modal-card glass strong-glass"><div class="modal-head"><div><p class="eyebrow">WELCOME BACK</p><h2>Session complete</h2></div><button type="button" class="close-button" data-v3-close="v3PostDialog">×</button></div><div id="v3PostContent"></div></div></dialog>`);
    if(!$('#v3SettingsDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="v3SettingsDialog" class="modal"><div class="modal-card glass strong-glass"><div class="modal-head"><div><p class="eyebrow">V3 SETTINGS</p><h2>Launch behavior</h2></div><button type="button" class="close-button" data-v3-close="v3SettingsDialog">×</button></div><div class="v3-settings"><label class="v3-setting"><span>Smart preflight when network is stale</span><input id="v3PrefPreflight" type="checkbox"></label><label class="v3-setting"><span>Auto-run lightweight quick check</span><input id="v3PrefQuick" type="checkbox"></label><label class="v3-setting"><span>Show post-game summary</span><input id="v3PrefPost" type="checkbox"></label></div><button id="v3SaveSettings" type="button" class="primary-button">Save Settings</button></div></dialog>`)
  }

  function gameDetail(g){if(!g)return;const s=stats(g),r=readiness(g),n=latestNet(),fav=favs().includes(String(g.id));$('#v3GameTitle').textContent=g.name;$('#v3GameContent').innerHTML=`<div class="v3-hero">${art(g)}<div><span class="v3-score"><b>${r.score}</b>/100 ready</span><h2>${esc(g.name)}</h2><p>${esc(g.seller||'App Store game')} · ${esc(profileLabel(g))}</p></div></div><div class="v3-chips">${r.checks.map(c=>`<span class="v3-chip ${c.good?'good':''}">${c.good?'✓ ':''}${esc(c.label)}</span>`).join('')}</div><div class="v3-stats"><div class="v3-stat"><span>Launches</span><strong>${s.launches}</strong></div><div class="v3-stat"><span>Estimated time</span><strong>${duration(s.total)}</strong></div><div class="v3-stat"><span>Avg session</span><strong>${s.launches?duration(s.avg):'—'}</strong></div></div><div class="v3-note"><strong>${esc(profileLabel(g))} launch policy</strong><p>${esc(policy(g).note)}. Warning at &gt;${policy(g).lat} ms latency or &gt;${policy(g).jit} ms jitter. Optional Shortcut branch: ${esc(policy(g).hint)}.</p></div><div class="v3-note"><strong>Current network</strong><p>${n?`${n.latency} ms · ${n.jitter} ms jitter · ${quality(n.latency,n.jitter).label} · ${fresh(g,n)?'fresh':'stale'}`:'No measurement yet.'}</p></div><div class="v3-actions"><button class="v3-mini" data-v3-favorite="${esc(g.id)}">${fav?'★ Favorite':'☆ Add Favorite'}</button><button class="v3-mini" data-v3-router-game="${esc(g.id)}">Router Recipe</button><button class="v3-mini" data-v3-quick="${esc(g.id)}">Quick Check</button><button class="v3-mini primary" data-v3-preflight="${esc(g.id)}">PLAY</button></div>`;if(!$('#v3GameDialog').open)$('#v3GameDialog').showModal()}

  function preflight(g,state='idle',msg=''){const n=preflightResult||latestNet(),f=fresh(g,n),q=n?quality(n.latency,n.jitter):null,w=n?warn(g,n):'',ok=launchReady(g),v=isVerified(g);$('#v3PreflightTitle').textContent=g.name;$('#v3PreflightContent').innerHTML=`<div class="v3-hero">${art(g)}<div><p class="eyebrow">${esc(policy(g).label.toUpperCase())}</p><h2>${esc(g.name)}</h2><p>${esc(policy(g).note)}</p></div></div><div class="v3-preflight"><div class="v3-line"><span>Launch route</span><strong class="${ok?'good':'warn'}">${deepLink(g)?'Direct link':ok?'Router configured':'Setup required'}</strong></div><div class="v3-line"><span>Game route</span><strong class="${v?'good':''}">${v?'Verified by prior session':'Not verified yet'}</strong></div><div class="v3-line"><span>Network</span><strong class="${q?.good&&f?'good':'warn'}">${n?`${n.latency} ms · ${n.jitter} ms · ${q.label}`:'Not measured'}</strong></div><div class="v3-line"><span>Profile</span><strong>${esc(profileLabel(g))}</strong></div></div>${state==='checking'?`<div class="v3-progress"><div id="v3QuickProgress"></div></div><p class="smart-note" id="v3QuickText">${esc(msg||'Checking connection…')}</p>`:''}${w?`<div class="smart-warning"><strong>Network warning</strong><br>${esc(w)}. You can still launch.</div>`:''}${!ok?`<div class="smart-warning">Launch route belum siap. Buka Router Assistant.</div>`:''}<div class="v3-actions" style="margin-top:14px"><button class="v3-mini" data-v3-quick="${esc(g.id)}" ${state==='checking'?'disabled':''}>${n?'Recheck':'Quick Check'}</button><button class="v3-mini" data-v3-router-game="${esc(g.id)}">Router</button><button class="v3-mini primary" data-v3-launch="${esc(g.id)}" ${!ok?'disabled':''}>Launch Game</button></div>`}
  async function runQuick(g){if(checking)return;checking=true;preflightResult=null;if(!$('#v3PreflightDialog').open)$('#v3PreflightDialog').showModal();preflight(g,'checking','Starting quick network check…');try{preflightResult=await quickCheck(g,(i,c)=>{const b=$('#v3QuickProgress'),t=$('#v3QuickText');if(b)b.style.width=`${Math.round(((i+1)/c)*100)}%`;if(t)t.textContent=`Latency sample ${i+1}/${c}…`});preflight(g,'done');sync()}catch(e){console.warn('v3 quick check',e);preflight(g,'error');$('#v3PreflightContent')?.insertAdjacentHTML('afterbegin',`<div class="smart-warning">Quick check gagal${e?.message==='offline'?': device offline':''}. Kamu masih bisa launch jika route siap.</div>`)}finally{checking=false}}
  function openPreflight(g){if(!g)return;preflightResult=null;if(!launchReady(g)){openRouter(g);return}const p=prefs(),n=latestNet();if(!p.preflight||fresh(g,n)){launch(g);return}$('#v3GameDialog')?.close();preflight(g);$('#v3PreflightDialog').showModal();if(p.quick)runQuick(g)}

  function branchSteps(g){const out=[`Jika Shortcut Input adalah “${routeKey(g)}”`];if(g.profile==='competitive')out.push('Optional: Set Focus → Gaming ON','Optional: Set Low Power Mode → OFF');else if(g.profile==='battery')out.push('Optional: Set Focus → Gaming ON','Optional: Set Low Power Mode → ON');else out.push('Optional: Set Focus → Gaming ON');out.push(`Buka App → ${g.name}`);return out}
  function openRouter(selected=null){const l=games(),v=verified(),r=router();$('#v3RouterContent').innerHTML=`<div class="v3-status-grid"><div class="v3-status"><span>Shortcut</span><strong>${esc(r.universalShortcut||'iPBooster Play')}</strong></div><div class="v3-status"><span>Router</span><strong>${r.universalReady?'Enabled':'Setup'}</strong></div><div class="v3-status"><span>Verified</span><strong>${l.filter(g=>v[g.id]?.verifiedAt).length}/${l.length}</strong></div></div><div class="v3-router-list">${l.map(g=>{const ok=Boolean(v[g.id]?.verifiedAt);return`<div class="v3-router-row"><div class="v3-router-row-head"><div><strong>${esc(g.name)}</strong><small>Route key: <span class="v3-code">${esc(routeKey(g))}</span> · ${esc(profileLabel(g))}</small></div><span class="v3-chip ${ok?'good':''}">${ok?'✓ Verified':'Unverified'}</span></div><small style="margin-top:8px">${branchSteps(g).map((s,i)=>`${i+1}. ${esc(s)}`).join('<br>')}</small></div>`}).join('')||'<div class="empty-state">No games in library.</div>'}</div><div class="v3-note"><strong>Profile behavior in v3</strong><p>Profiles change real web preflight freshness, sample count, and warning thresholds. iOS Focus/Low Power steps are optional Shortcut actions and are never claimed as applied unless you add them yourself.</p></div><div class="v3-actions"><button class="v3-mini" id="v3OpenRouter">Open iPBooster Play</button><button class="v3-mini" data-v3-settings>Launch Settings</button></div>`;if(!$('#v3RouterDialog').open)$('#v3RouterDialog').showModal()}

  function favorite(id){const s=new Set(favs()),k=String(id);s.has(k)?s.delete(k):s.add(k);save(K.favs,[...s]);if($('#v3GameDialog').open)gameDetail(gameById(id));sync()}
  function focusGame(){const l=games();if(!l.length)return null;const f=favs(),x=l.find(g=>f.includes(String(g.id)));if(x)return x;const last=sessions()[0];return last?(l.find(g=>String(g.id)===String(last.gameId))||l.find(g=>g.name===last.gameName)||l[0]):l[0]}

  function injectHome(){const home=$('[data-view="home"]');if(!home||$('#v3Control'))return;const el=document.createElement('section');el.id='v3Control';el.className='v3-control glass strong-glass';home.querySelector('.metrics-grid')?.insertAdjacentElement('afterend',el)}
  function renderHome(){const root=$('#v3Control');if(!root)return;const g=focusGame(),n=latestNet(),r=router();if(!g){root.innerHTML=`<div class="v3-head"><div><p class="eyebrow">V3 CONTROL CENTER</p><h3>Add your first game</h3><small>Game detail, preflight and analytics will appear here.</small></div><button class="v3-mini" data-tab="games">Games</button></div>`;return}const rd=readiness(g),s=stats(g);root.innerHTML=`<div class="v3-head"><div><p class="eyebrow">V3 CONTROL CENTER</p><h3>${rd.score>=80?'Ready to play':'Launch overview'}</h3><small>Real launcher readiness, not a CPU benchmark.</small></div><button class="v3-mini" data-v3-settings>⚙︎</button></div><div class="v3-status-grid"><div class="v3-status"><span>Router</span><strong>${r.universalReady?'Ready':'Setup'}</strong></div><div class="v3-status"><span>Network</span><strong>${n?`${n.latency} ms`:'No test'}</strong></div><div class="v3-status"><span>Sessions</span><strong>${s.launches}</strong></div></div><div class="v3-game">${art(g)}<div><strong>${esc(g.name)}</strong><small>${esc(profileLabel(g))} · ${rd.score}/100 readiness</small></div><div class="v3-actions"><button class="v3-mini" data-v3-detail="${esc(g.id)}">Details</button><button class="v3-mini primary" data-v3-preflight="${esc(g.id)}">Play</button></div></div>`}

  function injectRouterCard(){const view=$('[data-view="games"]');if(!view||$('#v3RouterCard'))return;const el=document.createElement('section');el.id='v3RouterCard';el.className='v3-router-card glass';($('#smartPlayCard')||view.querySelector('.page-intro'))?.insertAdjacentElement('afterend',el)}
  function renderRouterCard(){const root=$('#v3RouterCard');if(!root)return;const l=games(),v=verified(),count=l.filter(g=>v[g.id]?.verifiedAt).length;root.innerHTML=`<div><strong>Router & Profile Assistant</strong><small>${routerReady()?`Router enabled · ${count}/${l.length} routes verified by completed sessions`:'Finish If → Open App routing, then v3 can track verified launches.'}</small></div><button class="v3-mini ${routerReady()?'':'primary'}" data-v3-router>${routerReady()?'Review':'Setup'}</button>`}

  function injectLibrary(){ $$('#gameLibrary .library-row').forEach(row=>{const play=row.querySelector('[data-game-play]'),a=row.querySelector('.row-actions');if(!play||!a)return;const id=play.dataset.gamePlay;if(![...a.querySelectorAll('[data-v3-detail]')].some(x=>x.dataset.v3Detail===id)){const b=document.createElement('button');b.type='button';b.className='v3-details';b.dataset.v3Detail=id;b.textContent='Details';a.insertBefore(b,a.firstChild)}if(![...a.querySelectorAll('[data-v3-favorite]')].some(x=>x.dataset.v3Favorite===id)){const b=document.createElement('button');b.type='button';b.className=`v3-fav ${favs().includes(String(id))?'active':''}`;b.dataset.v3Favorite=id;b.textContent=favs().includes(String(id))?'★':'☆';a.insertBefore(b,a.firstChild)}})}

  function injectAnalytics(){const view=$('[data-view="sessions"]');if(!view||$('#v3Analytics'))return;const el=document.createElement('section');el.id='v3Analytics';el.className='v3-analytics glass';$('#sessionSummary')?.insertAdjacentElement('afterend',el)}
  const dayKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  function renderAnalytics(){const root=$('#v3Analytics');if(!root)return;const l=sessions(),days=[],now=new Date();for(let o=6;o>=0;o--){const d=new Date(now.getFullYear(),now.getMonth(),now.getDate()-o);days.push({key:dayKey(d),label:d.toLocaleDateString(undefined,{weekday:'short'}).slice(0,2),sec:0})}l.forEach(s=>{const b=days.find(d=>d.key===dayKey(new Date(Number(s.startedAt))));if(b)b.sec+=Number(s.durationSec)||0});const max=Math.max(...days.map(d=>d.sec),1),total=days.reduce((s,d)=>s+d.sec,0),launches=l.filter(x=>Number(x.startedAt)>=Date.now()-604800000).length;root.innerHTML=`<div class="v3-analytics-head"><div><strong>7-day activity</strong><small>Launcher-estimated gameplay only</small></div><div style="text-align:right"><strong>${duration(total)}</strong><small>${launches} launches</small></div></div><div class="v3-bars">${days.map(d=>`<div class="v3-bar-col"><div class="v3-bar-track" title="${esc(duration(d.sec))}"><div class="v3-bar" style="height:${Math.max(4,Math.round(d.sec/max*100))}%"></div></div><small>${esc(d.label)}</small></div>`).join('')}</div>`}

  function settings(){const p=prefs();$('#v3PrefPreflight').checked=p.preflight;$('#v3PrefQuick').checked=p.quick;$('#v3PrefPost').checked=p.post;$('#v3SettingsDialog').showModal()}
  function saveSettings(){save(K.prefs,{preflight:$('#v3PrefPreflight').checked,quick:$('#v3PrefQuick').checked,post:$('#v3PrefPost').checked});$('#v3SettingsDialog').close();toast('v3 launch settings saved.')}
  function markVerified(s){if(!s?.gameId||Number(s.durationSec)<15)return;const m=verified();m[s.gameId]={verifiedAt:Date.now(),sessionId:s.id||'',gameName:s.gameName||''};save(K.verified,m)}
  function postGame(){setTimeout(()=>{const s=sessions()[0];if(!s?.id||Number(s.durationSec)<15)return;markVerified(s);const seen=localStorage.getItem(K.seen);if(String(seen)===String(s.id)){sync();return}localStorage.setItem(K.seen,String(s.id));sync();if(Number(s.endedAt)&&Date.now()-Number(s.endedAt)>300000||!prefs().post)return;const L=load(K.lastLaunch,{}),n=String(L.gameId)===String(s.gameId)?L.network:null;$('#v3PostContent').innerHTML=`<div class="v3-post"><div class="big">${duration(s.durationSec)}</div><strong>${esc(s.gameName)}</strong><p>Launcher estimate from Play until iPBooster returned to foreground.</p>${n?`<div class="v3-chips" style="justify-content:center"><span class="v3-chip good">${esc(quality(n.latency,n.jitter).label)}</span><span class="v3-chip">${esc(n.latency)} ms</span><span class="v3-chip">${esc(n.jitter)} ms jitter</span><span class="v3-chip">${esc(profileLabel({profile:s.profile}))}</span></div>`:''}<button class="primary-button" data-v3-post-close>Done</button></div>`;if(!$('#v3PostDialog').open)$('#v3PostDialog').showModal()},1500)}

  function copy(){const v=$('.version-chip');if(v)v.textContent='v3';const t=$('#readinessText');if(t&&/Smart Play Router/i.test(t.textContent))t.textContent='Smart Play Router + real preflight checks + local session analytics.'}
  function sync(){injectHome();injectRouterCard();injectLibrary();injectAnalytics();renderHome();renderRouterCard();renderAnalytics();copy()}

  function bind(){
    document.addEventListener('click',e=>{
      const close=e.target.closest?.('[data-v3-close]');if(close){document.getElementById(close.dataset.v3Close)?.close();return}
      const d=e.target.closest?.('[data-v3-detail]');if(d){e.preventDefault();e.stopImmediatePropagation();gameDetail(gameById(d.dataset.v3Detail));return}
      const f=e.target.closest?.('[data-v3-favorite]');if(f){e.preventDefault();e.stopImmediatePropagation();favorite(f.dataset.v3Favorite);return}
      if(e.target.closest?.('[data-v3-router]')){e.preventDefault();openRouter();return}
      const rg=e.target.closest?.('[data-v3-router-game]');if(rg){e.preventDefault();openRouter(gameById(rg.dataset.v3RouterGame));return}
      if(e.target.closest?.('[data-v3-settings]')){e.preventDefault();settings();return}
      const q=e.target.closest?.('[data-v3-quick]');if(q){e.preventDefault();e.stopImmediatePropagation();const g=gameById(q.dataset.v3Quick);if(g){$('#v3GameDialog')?.close();preflight(g);if(!$('#v3PreflightDialog').open)$('#v3PreflightDialog').showModal();runQuick(g)}return}
      const p=e.target.closest?.('[data-v3-preflight]');if(p){e.preventDefault();e.stopImmediatePropagation();openPreflight(gameById(p.dataset.v3Preflight));return}
      const l=e.target.closest?.('[data-v3-launch]');if(l){e.preventDefault();e.stopImmediatePropagation();const g=gameById(l.dataset.v3Launch);if(g&&launchReady(g)){$('#v3PreflightDialog')?.close();launch(g)}return}
      if(e.target.closest?.('[data-v3-post-close]')){$('#v3PostDialog')?.close();return}
      const play=e.target.closest?.('[data-game-play]');if(play&&routerReady()){const g=gameById(play.dataset.gamePlay);if(!g)return;e.preventDefault();e.stopImmediatePropagation();openPreflight(g)}
    },true);
    $('#v3SaveSettings')?.addEventListener('click',saveSettings);
    $('#v3RouterDialog')?.addEventListener('click',e=>{if(e.target.id!=='v3OpenRouter')return;const r=router(),name=r.universalShortcut?.trim()||'iPBooster Play';location.href=`shortcuts://open-shortcut?name=${enc(name)}`});
    addEventListener('pageshow',postGame);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')postGame()})
  }

  function watch(){const o=new MutationObserver(()=>{clearTimeout(o.t);o.t=setTimeout(sync,80)});o.observe(document.body,{childList:true,subtree:true})}
  dialogs();sync();bind();watch();postGame();
})();